Repository ynput/ayon-core, pull requests merged in 2024-07, with the labels that each got.

#698 Houdini: Fix CreateHDA for Houdini 20+
  server_addon/houdini/client/ayon_houdini/plugins/create/create_hda.py
Labels: host: Houdini, size/XS, type: bug

#727 Maya: UDIM texture from Yeti Rig Collector can be searched correctly with absolute path
  server_addon/maya/client/ayon_maya/plugins/publish/collect_yeti_rig.py
Labels: host: Maya, size/XS, type: bug

#731 Chore: Removed Resolve addon
  server_addon/resolve/client/ayon_resolve/README.markdown
  server_addon/resolve/client/ayon_resolve/RESOLVE_API_v19.0B-build20.txt
  server_addon/resolve/client/ayon_resolve/__init__.py
  server_addon/resolve/client/ayon_resolve/addon.py
  server_addon/resolve/client/ayon_resolve/api/__init__.py
  server_addon/resolve/client/ayon_resolve/api/action.py
  server_addon/resolve/client/ayon_resolve/api/lib.py
  server_addon/resolve/client/ayon_resolve/api/menu.py
  server_addon/resolve/client/ayon_resolve/api/menu_style.qss
  server_addon/resolve/client/ayon_resolve/api/pipeline.py
  server_addon/resolve/client/ayon_resolve/api/plugin.py
  server_addon/resolve/client/ayon_resolve/api/testing_utils.py
  server_addon/resolve/client/ayon_resolve/api/todo-rendering.py
  server_addon/resolve/client/ayon_resolve/api/utils.py
  server_addon/resolve/client/ayon_resolve/api/workio.py
  server_addon/resolve/client/ayon_resolve/hooks/pre_resolve_last_workfile.py
  server_addon/resolve/client/ayon_resolve/hooks/pre_resolve_setup.py
  server_addon/resolve/client/ayon_resolve/hooks/pre_resolve_startup.py
  server_addon/resolve/client/ayon_resolve/otio/__init__.py
  server_addon/resolve/client/ayon_resolve/otio/davinci_export.py
  server_addon/resolve/client/ayon_resolve/otio/davinci_import.py
  server_addon/resolve/client/ayon_resolve/otio/utils.py
  server_addon/resolve/client/ayon_resolve/plugins/create/create_shot_clip.py
  server_addon/resolve/client/ayon_resolve/plugins/inventory/remove_unused_media_pool_items.py
  server_addon/resolve/client/ayon_resolve/plugins/load/load_clip.py
  server_addon/resolve/client/ayon_resolve/plugins/load/load_editorial_package.py
  server_addon/resolve/client/ayon_resolve/plugins/load/load_media.py
  server_addon/resolve/client/ayon_resolve/plugins/publish/extract_workfile.py
  server_addon/resolve/client/ayon_resolve/plugins/publish/precollect_instances.py
  server_addon/resolve/client/ayon_resolve/plugins/publish/precollect_workfile.py
  server_addon/resolve/client/ayon_resolve/startup.py
  server_addon/resolve/client/ayon_resolve/utility_scripts/AYON__Menu.py
  server_addon/resolve/client/ayon_resolve/utility_scripts/ayon_startup.scriptlib
  server_addon/resolve/client/ayon_resolve/utility_scripts/develop/OTIO_export.py
  server_addon/resolve/client/ayon_resolve/utility_scripts/develop/OTIO_import.py
  server_addon/resolve/client/ayon_resolve/utility_scripts/develop/OpenPype_sync_util_scripts.py
  server_addon/resolve/client/ayon_resolve/utils.py
  server_addon/resolve/client/ayon_resolve/version.py
  server_addon/resolve/package.py
  server_addon/resolve/server/__init__.py
  server_addon/resolve/server/imageio.py
  server_addon/resolve/server/settings.py
Labels: host: Resolve, type: feature, size/XXL

#728 Fix: dirmap wasn't using local site values
  client/ayon_core/host/dirmap.py
  client/ayon_core/settings/lib.py
Labels: size/XS, type: bug

#747 Tests: Standardize IS_TEST to AYON_IN_TESTS
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_aftereffects_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_blender_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_fusion_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_harmony_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_max_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_maya_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_publish_cache_job.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_publish_job.py
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: host: Maya, host: Harmony, host: Fusion, host: Blender, host: After Effects, host: 3dsmax, size/XS, module: Deadline

#734 Chore: Add collect resource path for texture outputs from Ornatrix implementation
  client/ayon_core/plugins/publish/collect_resources_path.py
Labels: size/XS, type: feature

#758 Burnins: Remove deprecated ffmpeg argument
  client/ayon_core/lib/transcoding.py
Labels: size/XS, type: enhancement

#729 Deadline: provide default user credential fields in studio settings
  server_addon/deadline/client/ayon_deadline/plugins/publish/collect_user_credentials.py
  server_addon/deadline/client/ayon_deadline/version.py
  server_addon/deadline/package.py
  server_addon/deadline/server/settings/main.py
Labels: size/XS, type: enhancement, module: Deadline

#760 Chore: Removed Deadline addon
  server_addon/deadline/client/ayon_deadline/__init__.py
  server_addon/deadline/client/ayon_deadline/abstract_submit_deadline.py
  server_addon/deadline/client/ayon_deadline/addon.py
  server_addon/deadline/client/ayon_deadline/lib.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/collect_deadline_server_from_instance.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/collect_default_deadline_server.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/collect_pools.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/collect_user_credentials.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/help/validate_deadline_connection.xml
  server_addon/deadline/client/ayon_deadline/plugins/publish/help/validate_deadline_pools.xml
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_aftereffects_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_blender_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_celaction_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_fusion_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_harmony_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_houdini_cache_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_houdini_render_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_max_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_maya_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_nuke_deadline.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_publish_cache_job.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/submit_publish_job.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/validate_deadline_connection.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/validate_deadline_pools.py
  server_addon/deadline/client/ayon_deadline/plugins/publish/validate_expected_and_rendered_files.py
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.ico
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.options
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.param
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/Ayon/Ayon.py
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/CelAction/CelAction.ico
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/CelAction/CelAction.param
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/CelAction/CelAction.py
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/GlobalJobPreLoad.py
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/HarmonyAYON/HarmonyAYON.ico
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/HarmonyAYON/HarmonyAYON.options
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/HarmonyAYON/HarmonyAYON.param
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/HarmonyAYON/HarmonyAYON.py
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.ico
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.options
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.param
  server_addon/deadline/client/ayon_deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
  server_addon/deadline/client/ayon_deadline/repository/readme.md
  server_addon/deadline/client/ayon_deadline/version.py
  server_addon/deadline/package.py
  server_addon/deadline/server/__init__.py
  server_addon/deadline/server/settings/__init__.py
  server_addon/deadline/server/settings/main.py
  server_addon/deadline/server/settings/publish_plugins.py
  server_addon/deadline/server/settings/site_settings.py
Labels: host: Nuke, host: Maya, host: Houdini, host: Harmony, host: Fusion, host: CelAction, host: Blender, host: After Effects, host: 3dsmax, module: Deadline, type: feature, size/XXL

#761 Publishing collectors: Ignore invalid representation ids
  client/ayon_core/plugins/publish/collect_input_representations_to_versions.py
  client/ayon_core/plugins/publish/collect_scene_loaded_versions.py
Labels: bug, size/XS, type: enhancement, type: bug

#759 Product name: Support task short name
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/create/product_name.py
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/control.py
  client/ayon_core/tools/publisher/models/create.py
Labels: size/XS, type: feature

#768 Templated Workfile: Fix argument in populate create placeholder
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: size/XS, type: bug

#746 Global: dirmap for non local nor studio sites
  client/ayon_core/host/dirmap.py
Labels: size/XS, type: bug

#764 Chore: Make sure udim in representation is not a list
  client/ayon_core/pipeline/load/utils.py
  client/ayon_core/plugins/publish/integrate.py
Labels: size/XS, type: enhancement

#769 UI Icons: Cache key is safely generated
  client/ayon_core/tools/utils/lib.py
Labels: size/XS, type: bug

#770 Chore: Remove 3dsMax addon (again)
  server_addon/max/client/ayon_max/api/lib.py
  server_addon/max/client/ayon_max/api/plugin.py
  server_addon/max/client/ayon_max/plugins/create/create_tycache.py
  server_addon/max/client/ayon_max/plugins/load/load_tycache.py
  server_addon/max/client/ayon_max/plugins/publish/collect_frame_range.py
  server_addon/max/client/ayon_max/plugins/publish/collect_members.py
  server_addon/max/client/ayon_max/plugins/publish/collect_tycache_attributes.py
  server_addon/max/client/ayon_max/plugins/publish/extract_pointcloud.py
  server_addon/max/client/ayon_max/plugins/publish/extract_tycache.py
  server_addon/max/client/ayon_max/plugins/publish/validate_frame_range.py
  server_addon/max/client/ayon_max/plugins/publish/validate_tyflow_data.py
  server_addon/max/server/settings/publishers.py
Labels: host: 3dsmax, type: enhancement, size/XL

#752 Loader tool: Filter by statuses
  client/ayon_core/tools/loader/ui/_multicombobox.py
  client/ayon_core/tools/loader/ui/products_delegates.py
  client/ayon_core/tools/loader/ui/products_model.py
  client/ayon_core/tools/loader/ui/products_widget.py
  client/ayon_core/tools/loader/ui/statuses_combo.py
  client/ayon_core/tools/loader/ui/window.py
  client/ayon_core/tools/utils/lib.py
Labels: type: feature, size/L

#366 Code: Improve type hints for Creators
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/create/legacy_create.py
  client/ayon_core/pipeline/create/product_name.py
  client/ayon_core/tools/utils/widgets.py
Labels: community, size/XS, type: enhancement

#772 Loader: Change placeholder text to "Version status filter..."
  client/ayon_core/tools/loader/ui/statuses_combo.py
Labels: size/XS, type: enhancement

#777 Chore: Reduce 'six' usage
  client/ayon_core/addon/base.py
  client/ayon_core/addon/interfaces.py
  client/ayon_core/host/dirmap.py
  client/ayon_core/host/host.py
  client/ayon_core/host/interfaces.py
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/lib/file_transaction.py
  client/ayon_core/lib/local_settings.py
  client/ayon_core/lib/path_templates.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/project_folders.py
  client/ayon_core/pipeline/publish/abstract_collect_render.py
  client/ayon_core/pipeline/publish/abstract_expected_files.py
  client/ayon_core/pipeline/schema/__init__.py
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
  client/ayon_core/plugins/publish/extract_burnin.py
  client/ayon_core/plugins/publish/extract_review.py
  client/ayon_core/plugins/publish/integrate.py
  client/ayon_core/style/__init__.py
  client/ayon_core/tools/common_models/hierarchy.py
  client/ayon_core/tools/launcher/abstract.py
  client/ayon_core/tools/loader/abstract.py
  client/ayon_core/tools/publisher/publish_report_viewer/window.py
  client/ayon_core/tools/workfiles/abstract.py
Labels: type: enhancement, size/S

#773 Delete old versions: Add confirm prompt to avoid accidental delete
  client/ayon_core/plugins/load/delete_old_versions.py
Labels: size/XS, type: enhancement, sponsored

#774 Workfile Template Builder: Allow Create Placeholder to define the 'active' state
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: size/XS, type: enhancement

#783 Loader tool: Fix filtering
  client/ayon_core/tools/loader/ui/products_delegates.py
  client/ayon_core/tools/loader/ui/products_model.py
  client/ayon_core/tools/loader/ui/products_widget.py
Labels: size/XS, type: bug

#795 Chore: Faster cli initalization
  client/ayon_core/cli.py
  client/ayon_core/cli_commands.py
Labels: size/XS, type: feature

#794 Tray: Singleton tray
  client/ayon_core/addon/README.md
  client/ayon_core/addon/__init__.py
  client/ayon_core/addon/base.py
  client/ayon_core/cli_commands.py
  client/ayon_core/modules/__init__.py
  client/ayon_core/modules/base.py
  client/ayon_core/modules/webserver/__init__.py
  client/ayon_core/modules/webserver/version.py
  client/ayon_core/modules/webserver/webserver_module.py
  client/ayon_core/tools/stdout_broker/broker.py
  client/ayon_core/tools/tray/__init__.py
  client/ayon_core/tools/tray/addons_manager.py
  client/ayon_core/tools/tray/lib.py
  client/ayon_core/tools/tray/ui/__init__.py
  client/ayon_core/tools/tray/ui/__main__.py
  client/ayon_core/tools/tray/ui/dialogs.py
  client/ayon_core/tools/tray/ui/host_console_listener.py
  client/ayon_core/tools/tray/ui/images/gifts.png
  client/ayon_core/tools/tray/ui/info_widget.py
  client/ayon_core/tools/tray/ui/tray.py
  client/ayon_core/tools/tray/webserver/__init__.py
  client/ayon_core/tools/tray/webserver/base_routes.py
  client/ayon_core/tools/tray/webserver/cors_middleware.py
  client/ayon_core/tools/tray/webserver/server.py
  client/ayon_core/tools/tray/webserver/structures.py
Labels: type: feature, size/L

#798 Tray: Force start tray
  client/ayon_core/cli.py
  client/ayon_core/cli_commands.py
  client/ayon_core/tools/tray/lib.py
Labels: size/XS, type: enhancement

#799 Tray: Make starting tray check faster
  client/ayon_core/tools/tray/lib.py
Labels: size/XS, type: enhancement

#800 Tray: Helper to make sure it is running
  client/ayon_core/tools/stdout_broker/broker.py
  client/ayon_core/tools/tray/__init__.py
  client/ayon_core/tools/tray/lib.py
  client/ayon_core/tools/tray/structures.py
  client/ayon_core/tools/tray/ui/addons_manager.py
  client/ayon_core/tools/tray/ui/tray.py
  client/ayon_core/tools/tray/webserver/__init__.py
Labels: size/XS, type: enhancement

#775 Enable Validate Outdated Containers by default for Fusion
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement

#797 Tray: Add username to info
  client/ayon_core/tools/tray/ui/tray.py
Labels: size/XS, type: enhancement

#793 Farm: replace in environment values requires a value
  client/ayon_core/hooks/pre_filter_farm_environments.py
  server/settings/main.py
Labels: size/S, type: feature

#801 Tray: Send messages to tray
  client/ayon_core/tools/tray/lib.py
  client/ayon_core/tools/tray/ui/tray.py
Labels: size/XS, type: enhancement

#802 Chore: Merge cli and cli_commands
  client/ayon_core/cli.py
  client/ayon_core/cli_commands.py
  client/ayon_core/pipeline/publish/__init__.py
  client/ayon_core/pipeline/publish/lib.py
Labels: type: enhancement, size/S

#792 Bugfix: loader support product type filter profiles
  client/ayon_core/tools/loader/abstract.py
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/loader/models/products.py
  client/ayon_core/tools/loader/ui/product_types_widget.py
  client/ayon_core/tools/loader/ui/window.py
  server/settings/tools.py
Labels: size/XS, type: bug

#832 Tweak grammar for "Addon is not available" due to outdated version for moved addon from core
  client/ayon_core/addon/base.py
Labels: size/XS, type: enhancement

#833 Update opencolorio version to ^2.3.2 in pyproject.toml
  client/pyproject.toml
Labels: size/XS
