Repository ynput/ayon-core, pull requests merged in 2024-09, with the labels that each got.

#855 Publisher: Screen capture fixes
  client/ayon_core/tools/publisher/widgets/screenshot_widget.py
Labels: type: enhancement, size/S

#786 Better validation report when publishing from unsaved workfile
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
  client/ayon_core/plugins/publish/collect_scene_version.py
  client/ayon_core/plugins/publish/validate_file_saved.py
Labels: size/XS, type: enhancement

#868 Log message: Avoid double quotes around paths
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
Labels: size/XS, type: enhancement

#863 Chore: More strict ruff
  client/ayon_core/hooks/pre_global_host_data.py
  client/ayon_core/lib/path_templates.py
  client/ayon_core/plugins/publish/collect_context_entities.py
  client/ayon_core/plugins/publish/extract_review.py
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
  client/ayon_core/plugins/publish/validate_file_saved.py
  client/ayon_core/tools/tray/lib.py
  pyproject.toml
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement

#845 Provided unique file prefix in Extract OTIO review
  client/ayon_core/plugins/publish/extract_otio_review.py
Labels: size/XS, type: enhancement

#872 Workfile template build: Allow empty representation name
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: size/XS, type: enhancement

#873 Maya 2025: Should display scriptsmenu correctly instead of only search bar
  client/ayon_core/vendor/python/scriptsmenu/launchformaya.py
Labels: host: Maya, size/XS, type: bug

#875 Workfile template builder: Allow custom `resolve_template_path`
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: type: enhancement

#882 Allow `.tif` and `.tiff` extensions for review
  client/ayon_core/plugins/publish/extract_review.py
Labels: size/XS, type: enhancement

#885 Avoid redefinition of variable name in burnin OTIO
  client/ayon_core/scripts/slates/slate_base/items.py
Labels: size/XS, type: bug

#880 Create: Allow context promise for editorial workflow
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/structures.py
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/control.py
  client/ayon_core/tools/publisher/models/create.py
  client/ayon_core/tools/publisher/widgets/card_view_widgets.py
  client/ayon_core/tools/publisher/widgets/list_view_widgets.py
  client/ayon_core/tools/publisher/widgets/widgets.py
  client/ayon_core/tools/publisher/window.py
Labels: type: enhancement, size/S

#884 Fix attribute_definitions.py typos
  client/ayon_core/lib/attribute_definitions.py
Labels: size/XS, type: maintenance

#865 Chore: Remove OpenPype compatibility
  client/ayon_core/__init__.py
  client/ayon_core/addon/base.py
  client/ayon_core/cli.py
  client/ayon_core/lib/__init__.py
  client/ayon_core/lib/execute.py
  client/ayon_core/lib/local_settings.py
  client/ayon_core/modules/__init__.py
  client/ayon_core/modules/base.py
  client/ayon_core/modules/click_wrap.py
  client/ayon_core/modules/interfaces.py
  client/ayon_core/pipeline/__init__.py
  client/ayon_core/pipeline/context_tools.py
  client/ayon_core/pipeline/publish/README.md
  client/ayon_core/pipeline/publish/__init__.py
  client/ayon_core/pipeline/publish/lib.py
  client/ayon_core/pipeline/publish/publish_plugins.py
  client/ayon_core/pipeline/tempdir.py
  client/ayon_core/plugins/publish/collect_addons.py
  client/ayon_core/plugins/publish/collect_input_representations_to_versions.py
  client/ayon_core/plugins/publish/collect_rendered_files.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
  client/ayon_core/resources/__init__.py
  client/ayon_core/settings/local_settings.md
  client/ayon_core/style/style.css
  client/ayon_core/tools/publisher/widgets/overview_widget.py
  client/ayon_core/tools/publisher/widgets/widgets.py
  client/ayon_core/tools/pyblish_pype/util.py
  client/ayon_core/tools/tray/ui/addons_manager.py
  client/ayon_core/tools/utils/__init__.py
  client/ayon_core/tools/utils/lib.py
Labels: type: enhancement, size/M

#894 Create Context: Use transient data for promised context
  client/ayon_core/pipeline/create/structures.py
Labels: size/XS, type: enhancement

#883 Get context attributes from current task entity instead of folder
  client/ayon_core/plugins/publish/collect_context_entities.py
Labels: size/XS, type: enhancement

#44 Add Loader OTIO export action - AY-3020
  client/ayon_core/plugins/load/export_otio.py
  client/ayon_core/tests/conftest.py
  client/ayon_core/tests/plugins/load/test_export_otio.py
  client/ayon_core/tests/resources/lib/transcoding/a01vfxd_sh010_plateP01_v002.1013.exr
  client/ayon_core/tests/resources/lib/transcoding/a01vfxd_sh010_plateP01_v002.mov
  pyproject.toml
Labels: host: Resolve, type: enhancement, size/S

#861 Publisher: Exception for artist error
  client/ayon_core/pipeline/__init__.py
  client/ayon_core/pipeline/publish/README.md
  client/ayon_core/pipeline/publish/__init__.py
  client/ayon_core/pipeline/publish/publish_plugins.py
  client/ayon_core/style/style.css
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/control.py
  client/ayon_core/tools/publisher/models/__init__.py
  client/ayon_core/tools/publisher/models/publish.py
  client/ayon_core/tools/publisher/widgets/publish_frame.py
  client/ayon_core/tools/publisher/widgets/report_page.py
  client/ayon_core/tools/utils/widgets.py
Labels: type: enhancement, size/S

#908 Fix: Not removing absolute path in Maya DL submission
  client/ayon_core/pipeline/farm/pyblish_functions.py
Labels: size/XS, type: bug

#907 Deliver versions: Remove legacy code
  client/ayon_core/plugins/load/delivery.py
Labels: size/XS, type: maintenance

#913 Fix: download referenced representations when synchronizing workfile via SiteSync addon
  client/ayon_core/plugins/publish/integrate_inputlinks.py
  client/ayon_core/tools/loader/models/sitesync.py
Labels: size/XS, type: bug

#919 Add cinema4d to OCIO prelaunch hook
  client/ayon_core/hooks/pre_ocio_hook.py
  client/ayon_core/pipeline/constants.py
  client/ayon_core/plugins/publish/validate_file_saved.py
Labels: community, size/XS, type: enhancement

#903 Integrator: Log the filepath if invalidated for being fullpath for clearer log
  client/ayon_core/plugins/publish/integrate.py
Labels: size/XS, type: enhancement

#906 Fix delivering UDIMs using {udim} in delivery template
  client/ayon_core/lib/path_tools.py
  client/ayon_core/plugins/load/delivery.py
Labels: size/XS, type: bug
