Repository ynput/ayon-core, pull requests merged in 2024-10, with the labels that each got.

#926 Chore: Remove 'HOST_WORKFILE_EXTENSIONS'
  client/ayon_core/pipeline/__init__.py
  client/ayon_core/pipeline/constants.py
Labels: size/XS, type: enhancement

#853 OIIO Transcode: Simplify Extract OIIO transcode settings
  client/ayon_core/plugins/publish/extract_color_transcode.py
  server/settings/conversion.py
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement

#834 Refactor OCIO config handling, introduce fallback mechanism
  client/ayon_core/pipeline/colorspace.py
  server/settings/conversion.py
  server/settings/main.py
Labels: type: enhancement, size/S

#916 Fix extract_otio_review extraction logic for corner-case media
  client/ayon_core/pipeline/editorial.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_embedded_tc_review.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_review.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_embedded_tc_review.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_handle_tail_review.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_review.json
  tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
Labels: type: bug, size/XL

#871 fix running builder on start if scene is the default empty scene
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: community, type: bug

#933 Push to Library Project taskType naming bugfix
  client/ayon_core/tools/push_to_project/models/integrate.py
Labels: community, size/XS, type: bug

#920 improved OIIO subimages handling
  client/ayon_core/lib/transcoding.py
Labels: community, size/XS, type: enhancement

#897 Fix wrong retimed detection on image sequence clip.
  client/ayon_core/pipeline/editorial.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  client/ayon_core/plugins/publish/extract_otio_trimming_video.py
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_embedded_tc.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_embedded_tc_review.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_no_handles.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_review.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_with_handles.json
  tests/client/ayon_core/pipeline/editorial/resources/legacy_img_sequence.json
  tests/client/ayon_core/pipeline/editorial/resources/movie_with_handles.json
  tests/client/ayon_core/pipeline/editorial/resources/multiple_review_clips.json
  tests/client/ayon_core/pipeline/editorial/resources/multiple_review_clips_gap.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_embedded_tc.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_embedded_tc_review.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_handle_tail_review.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_retimed_speed.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_review.json
  tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
  tests/conftest.py
  tools/manage.ps1
  tools/manage.sh
Labels: size/S, type: bug

#877 Publisher: Do not log to console
  client/ayon_core/pipeline/context_tools.py
  client/ayon_core/tools/publisher/models/publish.py
Labels: size/XS, type: enhancement

#936 Fix NTSC framerates floating issue comparison.
  client/ayon_core/pipeline/editorial.py
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_23.976_metadata.json
  tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
Labels: size/XS, type: bug

#938 Publisher: Remove pyblish exception log from records
  client/ayon_core/tools/publisher/models/publish.py
Labels: size/XS, type: bug

#939 Cinema4D: Open last workfile on launch
  client/ayon_core/hooks/pre_add_last_workfile_arg.py
Labels: community, size/XS, type: enhancement

#889 Attribute definitions: Positive argument names
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/tools/attribute_defs/widgets.py
  client/ayon_core/tools/publisher/widgets/widgets.py
Labels: community, size/XS, type: enhancement

#753 Experimental tool: Pyblish debug stepper
  client/ayon_core/tools/experimental_tools/pyblish_debug_stepper.py
  client/ayon_core/tools/experimental_tools/tools_def.py
Labels: community, size/S, type: feature

#954 Delivery: Fill hierarchy data unused during publishing
  client/ayon_core/pipeline/delivery.py
  client/ayon_core/plugins/load/delivery.py
Labels: type: enhancement, size/S

#955 Fix single frame publishing for publish job on farm (to Deadline from e.g. Maya)
  client/ayon_core/pipeline/farm/pyblish_functions.py
Labels: size/XS, type: enhancement, type: bug

#935 Create Context: Per instance attributes and Callbacks
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/lib/events.py
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/create/structures.py
  client/ayon_core/pipeline/publish/publish_plugins.py
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/control.py
  client/ayon_core/tools/publisher/models/__init__.py
  client/ayon_core/tools/publisher/models/create.py
  client/ayon_core/tools/publisher/widgets/card_view_widgets.py
  client/ayon_core/tools/publisher/widgets/create_widget.py
  client/ayon_core/tools/publisher/widgets/list_view_widgets.py
  client/ayon_core/tools/publisher/widgets/overview_widget.py
  client/ayon_core/tools/publisher/widgets/product_attributes.py
  client/ayon_core/tools/publisher/widgets/product_context.py
  client/ayon_core/tools/publisher/widgets/product_info.py
  client/ayon_core/tools/publisher/widgets/widgets.py
  client/ayon_core/tools/publisher/window.py
Labels: type: feature, size/XXL

#968 Create Attribute values: Implemented iter
  client/ayon_core/pipeline/create/structures.py
Labels: size/XS, type: enhancement

#974 Attribute defs: Fix serialize of text wihout regex
  client/ayon_core/lib/attribute_definitions.py
Labels: size/XS, type: bug

#976 Editorial: Prepare for new args and kwarg in EntiyHub
  client/ayon_core/plugins/publish/extract_hierarchy_to_ayon.py
Labels: size/XS, type: enhancement

#977 Delivery: Fix representation entity data
  client/ayon_core/pipeline/delivery.py
Labels: size/XS, type: bug

#960 USD Contribution Workflow: Show/hide attributes per instance based on status of other toggles
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
Labels: size/XS, type: enhancement

#967 Create Context: Helper function to get entities
  client/ayon_core/pipeline/create/context.py
Labels: type: enhancement, size/S
