Repository ynput/ayon-core, pull requests merged in 2024-08, with the labels that each got.

#781 Addons: Preparation steps for child processes
  client/ayon_core/addon/__init__.py
  client/ayon_core/addon/base.py
  client/ayon_core/addon/ui/process_ready_error.py
  client/ayon_core/addon/utils.py
  client/ayon_core/lib/execute.py
Labels: size/S, type: feature

#837 Tray: Start tray with different user
  client/ayon_core/tools/tray/lib.py
Labels: size/S, type: feature

#838 Tray: Logout closes tray
  client/ayon_core/tools/tray/lib.py
Labels: size/XS, type: bug

#836 Scene Inventory tool: All outdated containers use red color of version
  client/ayon_core/tools/sceneinventory/model.py
Labels: size/XS, type: enhancement

#843 Publish report viewer: Better popup button
  client/ayon_core/resources/images/popout.png
  client/ayon_core/tools/publisher/publish_report_viewer/widgets.py
Labels: size/XS, type: enhancement

#842 Chore: Storage and Local directories
  client/ayon_core/addon/base.py
  client/ayon_core/lib/__init__.py
  client/ayon_core/lib/local_settings.py
  client/ayon_core/pipeline/thumbnails.py
  client/ayon_core/tools/publisher/publish_report_viewer/window.py
  client/ayon_core/tools/tray/lib.py
Labels: size/S, type: feature

#840 Publish report viewer: Don't validate extension of dropped file
  client/ayon_core/tools/publisher/publish_report_viewer/window.py
Labels: type: enhancement

#846 Validate opening and closing brackets on Anatomy keys.
  client/ayon_core/lib/path_templates.py
Labels: host: cross, size/XS, type: bug

#850 Settings: Use 'title' instead of 'topic'
  server/settings/publish_plugins.py
Labels: size/XS, type: bug

#841 Use product name for render templates
  client/ayon_core/pipeline/create/product_name.py
  client/ayon_core/pipeline/farm/pyblish_functions.py
  client/ayon_core/pipeline/farm/pyblish_functions.pyi
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
  client/ayon_core/plugins/publish/help/validate_unique_subsets.xml
  client/ayon_core/plugins/publish/integrate.py
  server/settings/tools.py
Labels: type: enhancement, size/S, type: feature, sponsored

#849 Prepare process: Enhancements
  client/ayon_core/addon/base.py
  client/ayon_core/addon/utils.py
  client/ayon_core/lib/__init__.py
  client/ayon_core/lib/ayon_info.py
Labels: size/XS, type: enhancement

#851 Widgets: Line edit with hints
  client/ayon_core/style/style.css
  client/ayon_core/tools/publisher/widgets/create_widget.py
  client/ayon_core/tools/utils/__init__.py
  client/ayon_core/tools/utils/widgets.py
Labels: size/S, type: feature

#142 Publisher: Add plugin details widget
  client/ayon_core/style/style.css
  client/ayon_core/tools/publisher/models/publish.py
  client/ayon_core/tools/publisher/publish_report_viewer/report_items.py
  client/ayon_core/tools/publisher/publish_report_viewer/widgets.py
  client/ayon_core/tools/publisher/window.py
  client/ayon_core/tools/utils/__init__.py
  client/ayon_core/tools/utils/widgets.py
Labels: size/XS, type: enhancement

#854 Use proper aac argument for ExtractReview
  server/settings/publish_plugins.py
Labels: size/XS, type: bug

#779 Chore: Python 2 deprecation in lib
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/lib/events.py
  client/ayon_core/lib/file_transaction.py
  client/ayon_core/lib/local_settings.py
  client/ayon_core/lib/path_templates.py
  client/ayon_core/lib/python_2_comp.py
  client/ayon_core/lib/python_module_tools.py
Labels: type: enhancement, size/S

#857 Chore: Parenthesis in shell
  client/ayon_core/lib/execute.py
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: bug

#844 Create api: Restructure
  client/ayon_core/pipeline/create/__init__.py
  client/ayon_core/pipeline/create/changes.py
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/create/exceptions.py
  client/ayon_core/pipeline/create/legacy_create.py
  client/ayon_core/pipeline/create/product_name.py
  client/ayon_core/pipeline/create/structures.py
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/models/create.py
Labels: type: enhancement, size/XXL

#796 USD plugin: Don't crash plugin file because of missing dependency
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
Labels: size/XS, type: enhancement

#754 USD Contribution Workflow: Enable asset contributions to write AYON Entity URIs
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement
