Repository ynput/ayon-core, pull requests merged in 2024-11, with the labels that each got.

#980 Remove Python 2 compatibility code
  client/ayon_core/lib/log.py
  client/ayon_core/lib/path_tools.py
Labels: size/XS, type: maintenance

#981 Remove `Logger.mongo_process_id`
  client/ayon_core/lib/log.py
Labels: size/XS, type: maintenance

#982 Publisher: Display overridden vs default values of attributes
  client/ayon_core/style/data.json
  client/ayon_core/style/style.css
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/models/create.py
  client/ayon_core/tools/publisher/widgets/product_attributes.py
Labels: type: enhancement

#986 Publisher: Revert to default value
  client/ayon_core/style/style.css
  client/ayon_core/tools/attribute_defs/__init__.py
  client/ayon_core/tools/attribute_defs/_constants.py
  client/ayon_core/tools/attribute_defs/files_widget.py
  client/ayon_core/tools/attribute_defs/widgets.py
  client/ayon_core/tools/publisher/abstract.py
  client/ayon_core/tools/publisher/control.py
  client/ayon_core/tools/publisher/models/create.py
  client/ayon_core/tools/publisher/widgets/product_attributes.py
Labels: type: feature, size/M

#990 Publisher: Refresh of create/publish values under correct conditions
  client/ayon_core/tools/publisher/widgets/product_attributes.py
Labels: size/XS, type: bug

#995 Chore: Add type hints to attribute definitions
  client/ayon_core/lib/attribute_definitions.py
Labels: type: enhancement, size/S

#997 Use open -R for opening explorer on MacOS
  client/ayon_core/plugins/actions/open_file_explorer.py
Labels: community, size/XS, type: bug, sponsored

#999 Scene manager: Filter to outdated toggle does work
  client/ayon_core/tools/sceneinventory/model.py
  client/ayon_core/tools/sceneinventory/models/containers.py
Labels: size/XS, type: bug

#992 Attribute definitions: Fix FileDef value conversions
  client/ayon_core/lib/attribute_definitions.py
Labels: size/XS, type: bug

#1000 Fix loader load option box widgets
  client/ayon_core/tools/attribute_defs/widgets.py
Labels: size/XS, type: bug

#1002 Tray: Don't kill other processes
  client/ayon_core/tools/tray/lib.py
Labels: size/S, type: bug

#998 Fix support for scriptsmenu running commands in PySide6
  client/ayon_core/vendor/python/scriptsmenu/action.py
  client/ayon_core/vendor/python/scriptsmenu/launchformaya.py
Labels: host: Maya, size/XS, type: bug

#1009 Create: Required keys in Create Instance data
  client/ayon_core/pipeline/create/structures.py
  client/ayon_core/tools/publisher/models/create.py
Labels: size/XS, type: bug

#1008 Loader UI: Don't change selection on version combobox hover
  client/ayon_core/tools/loader/ui/products_delegates.py
Labels: size/XS, type: bug

#996 Editorial: Distribution of colorspaceData within instance resources and reviewables
  client/ayon_core/plugins/publish/collect_otio_review.py
  client/ayon_core/plugins/publish/collect_otio_subset_resources.py
  client/ayon_core/plugins/publish/extract_color_transcode.py
  client/ayon_core/plugins/publish/extract_colorspace_data.py
  client/ayon_core/plugins/publish/extract_otio_review.py
Labels: size/XS, type: bug, sponsored

#994 Show publish plug-in attributes based on `families` instead of only `productType`
  client/ayon_core/pipeline/publish/publish_plugins.py
Labels: size/XS, type: enhancement

#958 Filtering for specific frames for simple files representations
  client/ayon_core/pipeline/farm/pyblish_functions.py
Labels: size/XS, type: feature

#1022 Chore: Stricter ruff config
  client/ayon_core/addon/base.py
  client/ayon_core/cli.py
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/lib/local_settings.py
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/product_name.py
  client/ayon_core/pipeline/editorial.py
  client/ayon_core/pipeline/entity_uri.py
  client/ayon_core/pipeline/farm/pyblish_functions.py
  client/ayon_core/plugins/publish/collect_hierarchy.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  client/ayon_core/plugins/publish/validate_unique_subsets.py
  client/ayon_core/scripts/otio_burnin.py
  client/ayon_core/settings/lib.py
  client/ayon_core/tools/creator/widgets.py
  client/ayon_core/tools/launcher/models/actions.py
  client/ayon_core/tools/loader/ui/_multicombobox.py
  client/ayon_core/tools/loader/ui/products_model.py
  client/ayon_core/tools/publisher/widgets/overview_widget.py
  client/ayon_core/tools/publisher/widgets/product_context.py
  client/ayon_core/tools/publisher/widgets/tasks_model.py
  client/ayon_core/tools/publisher/window.py
  client/ayon_core/tools/sceneinventory/models/containers.py
  client/ayon_core/tools/utils/lib.py
  pyproject.toml
  server/settings/publish_plugins.py
  server/settings/tools.py
  tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
Labels: type: enhancement, size/S

#1021 Editorial: Don't require 'hierarchy' key on instance
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
Labels: type: enhancement

#1023 Chore: Set environment variables for farm
  client/ayon_core/pipeline/publish/__init__.py
  client/ayon_core/pipeline/publish/constants.py
  client/ayon_core/plugins/publish/collect_farm_env_variables.py
Labels: size/XS, type: enhancement

#1026 Fix audio extraction from OTIO timeline.
  client/ayon_core/plugins/publish/extract_otio_audio_tracks.py
Labels: host: Resolve, type: bug

#1031 Farm env: Collect correct values for farm
  client/ayon_core/plugins/publish/collect_farm_env_variables.py
Labels: size/XS, type: enhancement
