Repository ynput/ayon-core, pull requests merged in 2024-12, with the labels that each got.

#1034 Fix extract_otio_review
  client/ayon_core/plugins/publish/extract_otio_review.py
Labels: size/XS, type: bug

#778 Chore: Add 'parents' to folder template data
  client/ayon_core/lib/path_templates.py
  client/ayon_core/pipeline/template_data.py
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
Labels: size/XS, type: enhancement, sponsored

#1005 Load and manage products from a library project
  client/ayon_core/pipeline/load/utils.py
  client/ayon_core/tools/sceneinventory/control.py
  client/ayon_core/tools/sceneinventory/model.py
  client/ayon_core/tools/sceneinventory/models/containers.py
  client/ayon_core/tools/sceneinventory/models/sitesync.py
  client/ayon_core/tools/sceneinventory/switch_dialog/dialog.py
  client/ayon_core/tools/sceneinventory/view.py
Labels: type: enhancement, size/S

#1036 AY-7242_Implement review representations in OTIO subset resources.
  client/ayon_core/plugins/publish/collect_otio_subset_resources.py
Labels: size/XS, type: enhancement

#1037 Loader & Scene inventory: Ignore containers with invalid representation id
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/sceneinventory/models/containers.py
Labels: size/XS, type: bug

#1038 Fix missing slate frame in Deadline publish
  client/ayon_core/pipeline/farm/pyblish_functions.py
Labels: size/XS, type: bug, sponsored

#887 AY-971 Custom staging dir functionality migration
  client/ayon_core/pipeline/__init__.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/publish/constants.py
  client/ayon_core/pipeline/publish/lib.py
  client/ayon_core/pipeline/staging_dir.py
  client/ayon_core/pipeline/tempdir.py
  client/ayon_core/plugins/publish/collect_custom_staging_dir.py
  client/ayon_core/plugins/publish/collect_managed_staging_dir.py
  client/ayon_core/plugins/publish/extract_burnin.py
  client/ayon_core/plugins/publish/extract_color_transcode.py
  client/ayon_core/plugins/publish/extract_review.py
Labels: type: feature, size/M, sponsored

#1033 Attribute definitions: Fix context menu on sequence items
  client/ayon_core/tools/attribute_defs/files_widget.py
Labels: type: bug

#1042 Chore: Workfile template name filters by correct task type
  client/ayon_core/pipeline/workfile/path_resolving.py
Labels: size/XS, type: bug

#1041 AY-7222 Fix otio_review no handles and tempdir for Resolve
  client/ayon_core/pipeline/tempdir.py
  client/ayon_core/plugins/publish/extract_otio_review.py
Labels: host: Resolve, size/XS, type: bug, sponsored

#1043 Replace with published path, avoid changing the instance data
  client/ayon_core/pipeline/publish/lib.py
Labels: size/XS, type: bug

#1057 Launcher: Addon actions are shown
  client/ayon_core/addon/base.py
  client/ayon_core/addon/interfaces.py
  client/ayon_core/tools/launcher/models/actions.py
  client/ayon_core/tools/launcher/ui/window.py
Labels: size/XS, type: bug

#1054 Increment workfile even when no unsaved changes
  client/ayon_core/pipeline/context_tools.py
Labels: size/XS, type: enhancement

#1066 Store in instance data whether the staging dir set is a custom one
  client/ayon_core/pipeline/publish/lib.py
  client/ayon_core/pipeline/staging_dir.py
Labels: size/XS, type: enhancement

#1061 AY-6502_Fix Maya dirmap settings
  client/ayon_core/host/dirmap.py
Labels: size/XS, type: bug, sponsored
