Repository ynput/ayon-core, pull requests merged in 2025-06, with the labels that each got.

#1086 Cosmetics + minor optimization for `CleanUp` plugin
  client/ayon_core/plugins/publish/cleanup.py
Labels: community, size/XS, type: enhancement

#1319 Extract Review: Use data class for temp data to get some type hints
  client/ayon_core/plugins/publish/extract_review.py
Labels: community, type: enhancement, size/S

#1317 Scene inventory tool: Update error more visible
  client/ayon_core/tools/sceneinventory/view.py
Labels: community, size/XS, type: bug

#1226 Launcher tool: Use webactions
  client/ayon_core/lib/__init__.py
  client/ayon_core/lib/ayon_info.py
  client/ayon_core/lib/execute.py
  client/ayon_core/settings/lib.py
  client/ayon_core/style/style.css
  client/ayon_core/tools/attribute_defs/dialog.py
  client/ayon_core/tools/attribute_defs/widgets.py
  client/ayon_core/tools/launcher/abstract.py
  client/ayon_core/tools/launcher/control.py
  client/ayon_core/tools/launcher/models/actions.py
  client/ayon_core/tools/launcher/ui/actions_widget.py
  client/ayon_core/tools/launcher/ui/resources/__init__.py
  client/ayon_core/tools/launcher/ui/resources/options.png
  client/ayon_core/tools/launcher/ui/window.py
  client/ayon_core/tools/loader/ui/actions_utils.py
  client/ayon_core/tools/utils/__init__.py
  client/ayon_core/tools/utils/constants.py
  client/ayon_core/tools/utils/lib.py
  client/ayon_core/tools/utils/widgets.py
  client/pyproject.toml
  package.py
Labels: type: feature, size/M, bump minor

#1299 🏛️Product base types: feature support check function
  client/ayon_core/pipeline/__init__.py
  client/ayon_core/pipeline/compatibility.py
Labels: size/XS, type: enhancement, sponsored

#1330 Tools: Pinned projects in pipeline UIs
  client/ayon_core/tools/common_models/projects.py
  client/ayon_core/tools/launcher/control.py
  client/ayon_core/tools/launcher/ui/projects_widget.py
  client/ayon_core/tools/launcher/ui/window.py
  client/ayon_core/tools/utils/__init__.py
  client/ayon_core/tools/utils/projects_widget.py
  client/ayon_core/tools/utils/views.py
Labels: type: enhancement, size/M

#1292 Templated Workfile Build: support building from an AYON Entity URI instead of filepath
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: community, type: enhancement, size/S

#1222 Pre and post loader hooks
  client/ayon_core/pipeline/load/__init__.py
  client/ayon_core/pipeline/load/plugins.py
  client/ayon_core/pipeline/load/utils.py
  client/ayon_core/tools/loader/models/actions.py
Labels: size/S, type: feature, sponsored

#1332 Handles missing folder/task data safely
  client/ayon_core/hooks/pre_global_host_data.py
Labels: size/XS, type: bug

#1323 Loader tool: Add filtering bar with more filtering options
  client/ayon_core/style/style.css
  client/ayon_core/tools/common_models/__init__.py
  client/ayon_core/tools/common_models/hierarchy.py
  client/ayon_core/tools/common_models/projects.py
  client/ayon_core/tools/loader/abstract.py
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/loader/models/products.py
  client/ayon_core/tools/loader/ui/product_types_combo.py
  client/ayon_core/tools/loader/ui/products_delegates.py
  client/ayon_core/tools/loader/ui/products_model.py
  client/ayon_core/tools/loader/ui/products_widget.py
  client/ayon_core/tools/loader/ui/search_bar.py
  client/ayon_core/tools/loader/ui/statuses_combo.py
  client/ayon_core/tools/loader/ui/tasks_widget.py
  client/ayon_core/tools/loader/ui/window.py
  client/ayon_core/tools/utils/widgets.py
Labels: type: enhancement, size/L, sponsored

#1331 Launcher tool: Enhance UX with actions
  client/ayon_core/style/style.css
  client/ayon_core/tools/launcher/ui/actions_widget.py
Labels: type: enhancement, size/S

#1340 Settings: Refactor `conditionalEnum` -> `conditional_enum`
  server/settings/main.py
  server/settings/publish_plugins.py
Labels: community, size/XS, type: maintenance

#1193 Add simple Create Project Structure web action
  client/ayon_core/cli.py
  pyproject.toml
  server/__init__.py
  server/settings/main.py
Labels: size/XS, type: enhancement

#1337 Publisher: Variant name picker sort the existing variants list
  client/ayon_core/tools/publisher/widgets/create_widget.py
Labels: community, size/XS, type: enhancement

#1347 Farm Publish: Do not register publish plug-in paths twice
  client/ayon_core/pipeline/publish/lib.py
Labels: community, size/XS, type: enhancement

#1348 Create context: Updated type hints
  client/ayon_core/pipeline/create/context.py
Labels: type: enhancement, size/S
