Repository ynput/ayon-core, pull requests merged in 2025-07, with the labels that each got.

#1355 Fix `IPublishHost` import
  client/ayon_core/pipeline/create/context.py
Labels: community, size/XS, type: bug

#1362 Chore: Define logging config for AYON processes
  client/ayon_core/cli.py
Labels: size/XS, type: enhancement

#1364 Chore: Fix Python 3.7 in loader tool
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/loader/models/actions.py
  client/ayon_core/tools/loader/models/products.py
  client/ayon_core/tools/loader/models/selection.py
  client/ayon_core/tools/loader/models/sitesync.py
  client/ayon_core/tools/loader/ui/_multicombobox.py
  client/ayon_core/tools/loader/ui/products_delegates.py
  client/ayon_core/tools/loader/ui/products_widget.py
  client/ayon_core/tools/loader/ui/search_bar.py
  client/ayon_core/tools/loader/ui/window.py
Labels: community, size/XS, type: bug

#1370 Fix all characters of report being printed to new lines
  client/ayon_core/pipeline/publish/lib.py
Labels: size/XS, type: bug

#1366 Photoshop: new defaults for ExtractReview
  client/ayon_core/plugins/publish/extract_review.py
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: enhancement, sponsored

#1375 Add task_types to ExtractReview profile filtering
  client/ayon_core/plugins/publish/extract_review.py
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement, sponsored

#1378 Workfile: Fill extension in helper functions
  client/ayon_core/pipeline/workfile/utils.py
Labels: size/XS, type: bug

#1381 Integrate Input Links: Do not use deprecated `Logger.warn`, use `Logger.warning` instead
  client/ayon_core/plugins/publish/integrate_inputlinks.py
Labels: size/XS, type: enhancement

#1384 Workfiles: Save next version re-use comment
  client/ayon_core/pipeline/workfile/__init__.py
  client/ayon_core/pipeline/workfile/utils.py
Labels: size/XS, type: enhancement

#1385 Launcher tool: Pass variant to actions list
  client/ayon_core/tools/launcher/models/actions.py
Labels: type: enhancement

#1377 Use Workfiles API `save_next_version` in `version_up_current_workfile`
  client/ayon_core/pipeline/context_tools.py
Labels: size/XS, type: enhancement, sponsored

#1391 Publish: Hash publish plugin dirpath before storing to sys modules
  client/ayon_core/pipeline/publish/lib.py
Labels: size/XS, type: enhancement

#1397 Lib: Local settings code refactor
  client/ayon_core/lib/local_settings.py
Labels: community, type: enhancement
