Repository ynput/ayon-core, pull requests merged in 2025-05, with the labels that each got.

#1260 CI Update Bug Report: Change trigger event
  .github/workflows/update_bug_report.yml
Labels: size/XS, type: bug

#1255 Adds explicit resolution override to publisher
  client/ayon_core/plugins/publish/collect_explicit_resolution.py
  server/settings/publish_plugins.py
Labels: type: enhancement, size/S

#1115 Colorpsace: Update OCIO config options
  package.py
  server/settings/main.py
Labels: size/XS, type: enhancement, bump minor

#1265 Chore: Reverse product name key replacements
  client/ayon_core/pipeline/create/product_name.py
Labels: type: bug

#1233 Editorial: Updates OTIO review extract to improve quality
  client/ayon_core/plugins/publish/extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
Labels: size/XS, type: bug, sponsored

#1250 Improves thumbnail extraction reliability
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: type: bug, sponsored

#1272 Fixes ffmpeg seek argument
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: bug

#1273 Fixes: Uses correct fallback data key
  client/ayon_core/pipeline/colorspace.py
Labels: type: bug

#1120 Speed Up Publishing Times
  client/ayon_core/lib/file_transaction.py
  client/ayon_core/plugins/publish/integrate_hero_version.py
Labels: community, size/XS, type: enhancement

#1285 Staging Dir persistence log, change to debug level
  client/ayon_core/plugins/publish/collect_managed_staging_dir.py
Labels: size/XS, type: enhancement
