Repository ynput/ayon-core, pull requests merged in 2025-04, with the labels that each got.

#930 Offloaded delivery processing workflow changes
  client/ayon_core/plugins/publish/collect_audio.py
  client/ayon_core/plugins/publish/extract_burnin.py
  client/ayon_core/plugins/publish/extract_review.py
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: type: enhancement, type: feature

#1218 Launcher tool: Show only assigned tasks
  client/ayon_core/tools/common_models/hierarchy.py
  client/ayon_core/tools/launcher/abstract.py
  client/ayon_core/tools/launcher/control.py
  client/ayon_core/tools/launcher/ui/hierarchy_page.py
  client/ayon_core/tools/launcher/ui/window.py
  client/ayon_core/tools/utils/folders_widget.py
  client/ayon_core/tools/utils/tasks_widget.py
Labels: type: enhancement, size/S, type: feature, sponsored

#1221 Fix: add python 3.7 support to loader tool again
  client/ayon_core/tools/loader/ui/product_types_combo.py
Labels: size/XS, type: bug

#1148 Chore: Environment variables in roots
  client/ayon_core/hooks/pre_global_host_data.py
  client/ayon_core/pipeline/anatomy/__init__.py
  client/ayon_core/pipeline/anatomy/exceptions.py
  client/ayon_core/pipeline/anatomy/roots.py
Labels: size/XS, type: feature, sponsored

#1228 Tools: Change how thumbnails are received
  client/ayon_core/pipeline/thumbnails.py
  client/ayon_core/tools/common_models/thumbnails.py
  client/ayon_core/tools/loader/abstract.py
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/loader/ui/window.py
Labels: size/S, type: bug

#1219 Create context: Set publish attributes values
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/structures.py
Labels: type: enhancement

#1141 Host: Version up current workfile handles empty workdir
  client/ayon_core/pipeline/context_tools.py
  client/ayon_core/pipeline/workfile/__init__.py
  client/ayon_core/pipeline/workfile/utils.py
Labels: size/XS, type: bug

#1231 Delete poetry.lock
  .gitignore
  poetry.lock
Labels: size/XL, type: maintenance

#1236 Chore: Update ffmpeg commands
  client/ayon_core/plugins/publish/extract_thumbnail.py
  client/ayon_core/plugins/publish/extract_thumbnail_from_source.py
Labels: size/XS, type: bug

#1239 Tools: Fix thumbnails output value type
  client/ayon_core/tools/common_models/thumbnails.py
Labels: size/XS, type: bug

#1237 Chore: Fix thumbnail upload
  client/ayon_core/plugins/publish/integrate_thumbnail.py
Labels: size/XS, type: bug

#1235 Update ruff action and take the ruff version from pyproject
  .github/workflows/pr_linting.yml
Labels: size/XS, type: maintenance

#1238 Fixes issue with original directory lookup
  client/ayon_core/plugins/publish/integrate.py
Labels: size/XS, type: bug

#1242 Fixes thumbnail creation logic
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: bug, sponsored

#1247 Extract Thumbnail: Fix original intnetion of thumbnail created logging
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: bug

#1244 Chore: Ruff add preview and docstring convetion
  client/ayon_core/addon/utils.py
  client/ayon_core/cli.py
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/lib/ayon_connection.py
  client/ayon_core/lib/terminal.py
  client/ayon_core/lib/vendor_bin_utils.py
  client/ayon_core/pipeline/create/context.py
  client/ayon_core/pipeline/create/structures.py
  client/ayon_core/pipeline/delivery.py
  client/ayon_core/pipeline/farm/pyblish_functions.py
  client/ayon_core/pipeline/schema/__init__.py
  client/ayon_core/pipeline/staging_dir.py
  client/ayon_core/pipeline/workfile/path_resolving.py
  client/ayon_core/plugins/load/delete_old_versions.py
  client/ayon_core/plugins/load/export_otio.py
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
  client/ayon_core/plugins/publish/collect_farm_env_variables.py
  client/ayon_core/plugins/publish/collect_hierarchy.py
  client/ayon_core/plugins/publish/collect_otio_subset_resources.py
  client/ayon_core/plugins/publish/extract_review.py
  client/ayon_core/plugins/publish/integrate.py
  client/ayon_core/plugins/publish/integrate_resources_path.py
  client/ayon_core/scripts/otio_burnin.py
  client/ayon_core/scripts/slates/slate_base/base.py
  client/ayon_core/scripts/slates/slate_base/items.py
  client/ayon_core/tools/console_interpreter/ui/widgets.py
  client/ayon_core/tools/creator/window.py
  client/ayon_core/tools/experimental_tools/pyblish_debug_stepper.py
  client/ayon_core/tools/loader/ui/window.py
  client/ayon_core/tools/publisher/models/create.py
  client/ayon_core/tools/publisher/models/publish.py
  client/ayon_core/tools/tray/lib.py
  client/ayon_core/tools/utils/tasks_widget.py
  client/ayon_core/tools/workfiles/models/workfiles.py
  pyproject.toml
  tests/client/ayon_core/pipeline/editorial/test_collect_otio_frame_ranges.py
  tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
Labels: type: enhancement, size/S

#1214 Allow disabling removal of rendered files on farm renders
  client/ayon_core/plugins/publish/collect_rendered_files.py
  server/settings/publish_plugins.py
Labels: community, size/XS, type: enhancement

#1248 Remove redundant duplicate lines of code
  client/ayon_core/pipeline/farm/pyblish_functions.py
Labels: community, size/XS, type: maintenance

#1253 Launcher tool: Check for all project filters
  client/ayon_core/tools/utils/projects_widget.py
Labels: size/XS, type: bug

#1191 Remove deprecated `StdOutBroker` import fallback
  client/ayon_core/tools/stdout_broker/app.py
  package.py
Labels: community, size/XS, type: enhancement

#1257 ExtractOIIOTranscode: Allow to process sequence of files in one `oiiotool` call
  client/ayon_core/plugins/publish/extract_color_transcode.py
Labels: community, size/XS, type: bug

#1259 Chore: Ruff config file and ruff version
  pyproject.toml
  ruff.toml
Labels: type: enhancement, size/S

#1251 Try extract thumbnail from available representations on instance
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: enhancement

#1216 Used new enum for template names from Anatomy
  package.py
  server/settings/publish_plugins.py
  server/settings/tools.py
Labels: size/XS, type: enhancement, bump minor

#1189 Remove deprecated `convert_for_ffmpeg`
  client/ayon_core/lib/__init__.py
  client/ayon_core/lib/transcoding.py
Labels: community, type: enhancement, size/S
