Repository ynput/ayon-core, pull requests merged in 2025-08, with the labels that each got.

#1396 Local settings: Capture 'ItemNotFoundException' error if possible
  client/ayon_core/lib/local_settings.py
Labels: type: bug

#1401 Workfiles: Make sure workdir exists
  client/ayon_core/host/interfaces/workfiles.py
Labels: size/XS, type: bug, sponsored

#1399 Addons: Plugin paths interface
  client/ayon_core/addon/base.py
  client/ayon_core/addon/interfaces.py
Labels: community, size/XS, type: enhancement

#1383 Linked assets/folders in template builder
  client/ayon_core/pipeline/load/plugins.py
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: size/XS, type: enhancement

#1411 Nice Checkbox: Small enhancements of Nice Checkbox
  client/ayon_core/tools/utils/nice_checkbox.py
Labels: community, type: enhancement, size/S

#1412 Chore: Remove legacy create
  client/ayon_core/pipeline/__init__.py
  client/ayon_core/pipeline/create/__init__.py
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/create/legacy_create.py
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
  client/ayon_core/tools/creator/__init__.py
  client/ayon_core/tools/creator/constants.py
  client/ayon_core/tools/creator/model.py
  client/ayon_core/tools/creator/widgets.py
  client/ayon_core/tools/creator/window.py
  client/ayon_core/tools/utils/host_tools.py
Labels: type: enhancement, size/S

#1413 Chore: Remove Subset manager tool
  client/ayon_core/tools/subsetmanager/README.md
  client/ayon_core/tools/subsetmanager/__init__.py
  client/ayon_core/tools/subsetmanager/model.py
  client/ayon_core/tools/subsetmanager/widgets.py
  client/ayon_core/tools/subsetmanager/window.py
  client/ayon_core/tools/utils/host_tools.py
Labels: type: enhancement, size/S

#1415 Supports hero versioning in the loader action
  client/ayon_core/plugins/load/create_hero_version.py
Labels: size/S, type: feature
