Repository ynput/ayon-core, pull requests merged in 2025-02, with the labels that each got.

#1109 Apply frame offset to timewarp to handle source frame offset.
  client/ayon_core/pipeline/editorial.py
  client/ayon_core/plugins/publish/collect_otio_review.py
  client/ayon_core/plugins/publish/collect_otio_subset_resources.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
Labels: type: bug, sponsored, tests

#1087 AY-6975 Consolidate retimes computation.
  client/ayon_core/pipeline/editorial.py
  client/ayon_core/plugins/publish/collect_otio_review.py
  client/ayon_core/plugins/publish/collect_otio_subset_resources.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_2x_speed.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_2x_speed_resolve.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_2x_time_warp.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_freeze_frame.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_multiple_tws.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_reverse_speed_0_7.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_reverse_speed_24_to_23.976fps.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_reverse_speed_no_tc.json
  tests/client/ayon_core/pipeline/editorial/resources/img_seq_tw_beyond_range.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_freeze_frame.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_reverse_speed_0_7.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_reverse_speed_2x.json
  tests/client/ayon_core/pipeline/editorial/resources/qt_timewarp.json
  tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
Labels: type: bug, size/XL, bump minor, tests

#1121 String template: Fix index validation for list values
  client/ayon_core/lib/path_templates.py
Labels: size/XS, type: bug

#1122 Create: Add helper 'get_template_data' to create context
  client/ayon_core/pipeline/create/context.py
Labels: size/XS, type: enhancement

#1103 Create: Auto-fill project entity in get product name if is not passed in
  client/ayon_core/pipeline/create/creator_plugins.py
Labels: size/XS, type: enhancement

#1123 Escape & on Windows in shell using ^& in `run_subprocess`
  client/ayon_core/lib/execute.py
Labels: community, size/XS, type: bug

#1124 Add substance designer as being part of the hosts in extract thumbnail
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: enhancement

#1128 Update ruff action
  .github/workflows/pr_linting.yml
Labels: size/XS, type: maintenance

#1136 UI: Nice checkbox uses odd sizes
  client/ayon_core/tools/utils/nice_checkbox.py
Labels: size/XS, type: enhancement

#1138 Attribute definitions: Multiselection EnumDef allows empty items
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/tools/attribute_defs/widgets.py
  client/ayon_core/tools/publisher/widgets/precreate_widget.py
Labels: size/XS, type: enhancement

#1108 Enum attribute definition: Allow placeholder text
  client/ayon_core/lib/attribute_definitions.py
  client/ayon_core/tools/attribute_defs/widgets.py
  client/ayon_core/tools/utils/__init__.py
  client/ayon_core/tools/utils/multiselection_combobox.py
  client/ayon_core/tools/utils/widgets.py
Labels: community, size/XS, type: enhancement

#1130 Chore: Pass 'AYON_USE_STAGING' to farm jobs
  client/ayon_core/plugins/publish/collect_farm_env_variables.py
Labels: size/XS, type: enhancement

#1145 Tools: Use task label if is set
  client/ayon_core/tools/common_models/hierarchy.py
  client/ayon_core/tools/utils/tasks_widget.py
Labels: size/XS, type: enhancement

#1133 Chore: Remove 'six' usage
  client/ayon_core/tools/pyblish_pype/model.py
  client/ayon_core/tools/pyblish_pype/util.py
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/iconic_font.py
Labels: size/XS, type: enhancement

#1127 Create Placeholder: Do not list AutoCreator and HiddenCreator
  client/ayon_core/pipeline/workfile/workfile_template_builder.py
Labels: size/XS, type: enhancement

#1150 Fix double quotes around outer elements in the logs
  client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
Labels: size/XS, type: enhancement

#1151 Extract OTIO Review: "Adding representations" log to debug level
  client/ayon_core/plugins/publish/extract_otio_review.py
Labels: size/XS, type: enhancement

#973 USD contribution: Set up different default values based on profiles
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
  server/settings/publish_plugins.py
Labels: type: enhancement, size/S

#1161 Create context: Ignore failed initialization of create plugin
  client/ayon_core/pipeline/create/context.py
Labels: size/XS, type: enhancement

#1157 Loader tool: Tasks filtering
  client/ayon_core/tools/loader/abstract.py
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/loader/models/products.py
  client/ayon_core/tools/loader/models/selection.py
  client/ayon_core/tools/loader/ui/_multicombobox.py
  client/ayon_core/tools/loader/ui/product_types_combo.py
  client/ayon_core/tools/loader/ui/product_types_widget.py
  client/ayon_core/tools/loader/ui/products_delegates.py
  client/ayon_core/tools/loader/ui/products_model.py
  client/ayon_core/tools/loader/ui/products_widget.py
  client/ayon_core/tools/loader/ui/statuses_combo.py
  client/ayon_core/tools/loader/ui/tasks_widget.py
  client/ayon_core/tools/loader/ui/window.py
  client/ayon_core/tools/utils/tasks_widget.py
  client/ayon_core/tools/utils/views.py
Labels: type: feature, size/XL, sponsored

#1060 Refactor OTIO frame range collection
  client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
  tests/client/ayon_core/pipeline/editorial/resources/timeline/timeline.json
  tests/client/ayon_core/pipeline/editorial/test_collect_otio_frame_ranges.py
Labels: size/XS, type: feature, tests
