Repository ynput/ayon-core, pull requests merged in 2025-03, with the labels that each got.

#1165 Chore: Add SXR to image extension
  client/ayon_core/lib/transcoding.py
Labels: size/XS, type: enhancement, sponsored

#1152 Add unit tests as part of CI/CD
  .github/workflows/pr_unittests.yaml
Labels: size/XS, type: enhancement

#1170 remove usage of a deprecated tag: `thumb-nuke`
  client/ayon_core/plugins/publish/extract_thumbnail.py
Labels: size/XS, type: maintenance

#1172 Allow setting the default USD Contribution enabled state per profile
  client/ayon_core/plugins/publish/extract_usd_layer_contributions.py
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement, sponsored

#1164 Removed frame recalculation for explicit frames
  client/ayon_core/pipeline/farm/pyblish_functions.py
  client/ayon_core/plugins/publish/extract_color_transcode.py
  client/ayon_core/plugins/publish/integrate.py
Labels: size/XS, type: bug, sponsored

#1185 Chore: Remove `pyblish pype` tool
  client/ayon_core/cli.py
  client/ayon_core/tools/pyblish_pype/__init__.py
  client/ayon_core/tools/pyblish_pype/__main__.py
  client/ayon_core/tools/pyblish_pype/app.css
  client/ayon_core/tools/pyblish_pype/app.py
  client/ayon_core/tools/pyblish_pype/awesome.py
  client/ayon_core/tools/pyblish_pype/constants.py
  client/ayon_core/tools/pyblish_pype/control.py
  client/ayon_core/tools/pyblish_pype/delegate.py
  client/ayon_core/tools/pyblish_pype/font/fontawesome/fontawesome-webfont.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/LICENSE.txt
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-Bold.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-BoldItalic.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-ExtraBold.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-ExtraBoldItalic.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-Italic.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-Light.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-LightItalic.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-Regular.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-Semibold.ttf
  client/ayon_core/tools/pyblish_pype/font/opensans/OpenSans-SemiboldItalic.ttf
  client/ayon_core/tools/pyblish_pype/i18n/pyblish_lite.pro
  client/ayon_core/tools/pyblish_pype/i18n/zh_CN.qm
  client/ayon_core/tools/pyblish_pype/i18n/zh_CN.ts
  client/ayon_core/tools/pyblish_pype/img/down_arrow.png
  client/ayon_core/tools/pyblish_pype/img/logo-extrasmall.png
  client/ayon_core/tools/pyblish_pype/img/tab-overview.png
  client/ayon_core/tools/pyblish_pype/img/tab-terminal.png
  client/ayon_core/tools/pyblish_pype/mock.py
  client/ayon_core/tools/pyblish_pype/model.py
  client/ayon_core/tools/pyblish_pype/settings.py
  client/ayon_core/tools/pyblish_pype/util.py
  client/ayon_core/tools/pyblish_pype/vendor/__init__.py
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/__init__.py
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/_version.py
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/animation.py
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/fonts/elusiveicons-webfont-charmap.json
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/fonts/elusiveicons-webfont.ttf
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/fonts/fontawesome-webfont-charmap.json
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/fonts/fontawesome-webfont.ttf
  client/ayon_core/tools/pyblish_pype/vendor/qtawesome/iconic_font.py
  client/ayon_core/tools/pyblish_pype/version.py
  client/ayon_core/tools/pyblish_pype/view.py
  client/ayon_core/tools/pyblish_pype/widgets.py
  client/ayon_core/tools/pyblish_pype/window.py
Labels: community, type: enhancement, size/XXL

#1190 Remove `python_2_comp.py`
  client/ayon_core/lib/python_2_comp.py
Labels: community, size/XS, type: enhancement

#1187 LoaderPlugin: Update docstring (takes no arguments on initialization) - cosmetics
  client/ayon_core/pipeline/load/plugins.py
Labels: community, size/XS, type: enhancement

#1196 Publish: Render frames calculation fix
  client/ayon_core/pipeline/farm/pyblish_functions.py
Labels: size/XS, type: bug

#1169 Create Project Folder Structure: support list of str for leaf folders
  client/ayon_core/pipeline/project_folders.py
Labels: community, size/XS, type: enhancement

#1192 Create context: Do not trigger publish attributes collection after each add bulk
  client/ayon_core/pipeline/create/context.py
Labels: size/XS, type: enhancement

#1201 Fix publish plugin discovery
  client/ayon_core/lib/python_module_tools.py
  client/ayon_core/pipeline/publish/lib.py
Labels: size/XS, type: bug

#1211 Utils widgets: Ceil height of 'ExpandingTextEdit'
  client/ayon_core/tools/utils/widgets.py
Labels: size/XS, type: enhancement, type: bug

#1212 Launcher: Make project filter field case insensitive
  client/ayon_core/tools/utils/projects_widget.py
Labels: community, size/XS, type: enhancement

#1182 Add "Artist Note" input field to Save Workfile prompt
  client/ayon_core/tools/workfiles/abstract.py
  client/ayon_core/tools/workfiles/control.py
  client/ayon_core/tools/workfiles/widgets/files_widget.py
  client/ayon_core/tools/workfiles/widgets/save_as_dialog.py
Labels: community, size/XS, type: enhancement

#1143 Implement Integrator to allow attaching reviewables to other products easily
  client/ayon_core/plugins/publish/integrate_attach_reviewable.py
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement

#1215 Feature/mkdocs-setup fixes
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  poetry.lock
  pyproject.toml
Labels: type: feature, size/L

#1107 Support uppercase extensions in ExtractReview plugin
  client/ayon_core/plugins/publish/extract_review.py
Labels: size/XS, type: bug
