Repository ynput/ayon-core, pull requests merged in 2025-01, with the labels that each got.

#1068 Launcher: Fix red dot for FORCE_NOT_OPEN_WORKFILE_ROLE to be drawn on wrong location if app is not on first row
  client/ayon_core/tools/launcher/ui/actions_widget.py
Labels: size/XS, type: bug

#1071 Fix Anatomy.format_all with unpadded int values.
  client/ayon_core/lib/path_templates.py
Labels: size/XS, type: bug

#1069 Chore: Staging dir enhancements
  client/ayon_core/pipeline/create/creator_plugins.py
  client/ayon_core/pipeline/publish/lib.py
  client/ayon_core/pipeline/staging_dir.py
Labels: type: enhancement

#1064 Fix OTIO range computation 23.976 fps rounding with embedded timecode
  client/ayon_core/pipeline/editorial.py
  client/ayon_core/plugins/publish/extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/resources/qt_23.976_embedded_long_tc.json
  tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
  tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
Labels: size/S, type: bug, tests

#1073 Chore: Set host name environment variable for farm jobs
  client/ayon_core/plugins/publish/collect_farm_env_variables.py
Labels: size/XS, type: bug

#1078 Publisher: Convert legacy instances UI does not display correctly
  client/ayon_core/tools/publisher/widgets/card_view_widgets.py
Labels: size/XS, type: bug

#1082 Update default order to match values in `CollectUSDLayerContributions`
  server/settings/publish_plugins.py
Labels: size/XS, type: bug

#1084 Report stagingDir_is_custom to apply_staging_dir
  client/ayon_core/pipeline/create/creator_plugins.py
Labels: size/XS, type: bug

#1085 Workfiles: Browse and Save As button only enabled when in valid context
  client/ayon_core/tools/workfiles/widgets/files_widget.py
Labels: size/XS, type: bug

#1089 Add substance designer support
  client/ayon_core/hooks/pre_add_last_workfile_arg.py
  client/ayon_core/hooks/pre_ocio_hook.py
  client/ayon_core/plugins/publish/collect_resources_path.py
Labels: size/XS, type: enhancement

#1092 Reduce margins on Workfiles tool due to nested layouts
  client/ayon_core/tools/workfiles/widgets/window.py
Labels: size/XS, type: enhancement

#1099 Tray: Server uses 127.0.0.1 instead of localhost
  client/ayon_core/tools/tray/webserver/server.py
Labels: community, size/XS, type: bug

#1070 Add BorisFX Silhouette support
  client/ayon_core/hooks/pre_add_last_workfile_arg.py
  client/ayon_core/hooks/pre_ocio_hook.py
  client/ayon_core/plugins/publish/validate_file_saved.py
  client/ayon_core/tools/utils/views.py
  client/ayon_core/tools/workfiles/models/workfiles.py
Labels: size/XS, type: enhancement, type: feature

#1105 Create: Use 'AYON_INSTANCE_ID' by default instead of 'AVALON_NSTANCE_ID'
  client/ayon_core/pipeline/create/legacy_create.py
  client/ayon_core/pipeline/create/structures.py
Labels: size/XS, type: enhancement

#1102 Add Silhouette host to defaults of version and outdated containers validators
  server/settings/publish_plugins.py
Labels: size/XS, type: enhancement

#1104 Publisher: Report page can stretch logs
  client/ayon_core/style/style.css
  client/ayon_core/tools/publisher/widgets/report_page.py
Labels: community, size/XS, type: enhancement

#1110 Create: Allow to pass in transient data on instance creation
  client/ayon_core/pipeline/create/structures.py
Labels: size/XS, type: enhancement

#1112 Fix [clip_media] reviewable.
  client/ayon_core/plugins/publish/collect_otio_review.py
  client/ayon_core/plugins/publish/collect_otio_subset_resources.py
  client/ayon_core/plugins/publish/extract_otio_review.py
Labels: size/XS, type: bug

#1114 Add support for `optional_tooltip` attribute on `OptionalPyblishPluginMixin`
  client/ayon_core/pipeline/publish/publish_plugins.py
Labels: community, size/XS, type: enhancement
