Repository ynput/ayon-core, pull requests merged in 2025-09, with the labels that each got.

#1426 OCIO: Use "max" for host group to get the correct ocio environment variable
  client/ayon_core/hooks/pre_ocio_hook.py
Labels: size/XS, type: bug

#1429 Resolve environment variables in dev bundle addon paths
  client/ayon_core/addon/base.py
Labels: size/XS, type: enhancement

#1435 Loader: Product type icons
  client/ayon_core/tools/common_models/__init__.py
  client/ayon_core/tools/common_models/projects.py
  client/ayon_core/tools/loader/abstract.py
  client/ayon_core/tools/loader/control.py
  client/ayon_core/tools/loader/models/products.py
  client/ayon_core/tools/loader/ui/products_model.py
  client/ayon_core/tools/sceneinventory/control.py
  client/ayon_core/tools/sceneinventory/model.py
  client/ayon_core/tools/sceneinventory/models/containers.py
Labels: type: enhancement

#1439 Loader: Elide status name text
  client/ayon_core/tools/utils/delegates.py
Labels: size/XS, type: enhancement

#1434 Launcher: Show task workfiles
  client/ayon_core/hooks/pre_add_last_workfile_arg.py
  client/ayon_core/pipeline/actions.py
  client/ayon_core/tools/launcher/abstract.py
  client/ayon_core/tools/launcher/control.py
  client/ayon_core/tools/launcher/models/__init__.py
  client/ayon_core/tools/launcher/models/actions.py
  client/ayon_core/tools/launcher/models/selection.py
  client/ayon_core/tools/launcher/models/workfiles.py
  client/ayon_core/tools/launcher/ui/actions_widget.py
  client/ayon_core/tools/launcher/ui/hierarchy_page.py
  client/ayon_core/tools/launcher/ui/window.py
  client/ayon_core/tools/launcher/ui/workfiles_page.py
Labels: type: feature

#1452 Launcher: Fix form handling
  client/ayon_core/tools/launcher/ui/actions_widget.py
Labels: size/XS, type: bug
